### ISSUE TITLE
Missing CSS files

### ISSUE THREAD

**Issue by MichielDeMey** [pbock/bahnmap#1]
Both `dist/assets/css/skeleton.css` and `dist/assets/css/skeleton.css`
are missing from the repo, which will break the Makefile.

```
make: *** No rule to make target `dist/assets/css/skeleton.css', needed by `dist'.  Stop.
```

**Comment by pbock** [comment]
Thanks! The Makefile was carried over from an old project that had those files and I forgot to delete them. Fixed now.
